name: property_returns
description: Property Returns

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.10.1
  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+1
  flutter_bloc: ^0.11.0
  equatable: ^0.2.0
  meta: ^1.1.6
  font_awesome_flutter: ^8.4.0
  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3
  intl: ^0.15.8
  datetime_picker_formfield: ^0.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family:  MyIcons
        fonts:
         - asset: lib/fonts/MyIcons.ttf