/// Flutter icons MyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData check = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add_a_photo = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData add_circle = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData add_box = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData add_circle_outline = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData arrow_back = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData arrow_downward = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData arrow_forward = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData arrow_upward = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData assessment = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData attach_file = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData call = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData check_box = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData check_circle = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData create = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData done = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData error_outline = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData gps_fixed = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData person_add = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData person_outline = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData print = const IconData(0xe817, fontFamily: _kFontFam);
}
